* Metadata Converters
The Metadata Converters project provides open source utilities that convert among various metadata formats.

The first utility converts [[http://www.blaise.com/][Blaise(r)]] source code to [[http://www.colectica.com/ddi][DDI 3]].
** Blaise to DDI Converter
The Blaise to DDI Converter creates DDI 3 metadata from Blaise source code.
*** Features
The Blaise to DDI Converter creates the following DDI 3 metadata from a Blaise data model.

- Category
- CategoryScheme
- Code
- CodeScheme
- QuestionItem
- QuestionScheme
- ControlConstructScheme
- Instrument
*** Usage
#+BEGIN_QUOTE
BlaiseToDDI.exe inputFile.bla outputFile.xml
#+END_QUOTE
** License
The Metadata Converters may be used under the terms of the Lesser GNU Public License (LGPL).
** Support, Enhancements, and Integration
We are happy to provide professional support, enhance the converters to work with your data, or help you integrate the converters into your systems. Please [[http://www.colectica.com/contact][contact us]] and let us know how we can help.
** Additional Converters
What other metadata formats would you like to convert? We are happy to hear your ideas for new converters to add to the project. Please [[http://www.colectica.com/contact][get in touch]].
